## Student Attendance Analytics with Pandas

In [1]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [5]:
df = pd.read_excel(r"C:\Users\Shri Raksha Bhat\Desktop\project\aids_attendance (1).xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW23AD50,SRAJAN S,Data Science & GenAI - 3nd Yr- AI&DS,11,0,11,0,0%,Critical,33 more,Never,11
1,4MW24AD001,ADITHYA S POOJARY,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4,0,64%,Critical,5 more,2026-10-07,0
2,4MW24AD002,ANKITHA PRASANNA NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,11,0,0,100%,Safe,✓ Met,2026-10-07,0
3,4MW24AD003,ANUSHA KOTEGAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91%,Safe,✓ Met,2026-10-07,0
4,4MW24AD004,ANVITA RAMESH NAIK,Data Science & GenAI - 3nd Yr- AI&DS,11,9,2,0,82%,Warning,✓ Met,2026-10-07,0
...,...,...,...,...,...,...,...,...,...,...,...,...
57,4MW24AD059,ZEHA AYESHA,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,90%,Safe,✓ Met,2026-10-07,0
58,4MW24AD060,AMITH G PALANDYE,Data Science & GenAI - 3nd Yr- AI&DS,10,0,10,0,0%,Critical,30 more,Never,10
59,4MW24AD061,AMOGH BHASKAR NAIK,Data Science & GenAI - 3nd Yr- AI&DS,10,5,5,0,50%,Critical,10 more,2026-10-07,0
60,4MW24AD062,CHANDISH,Data Science & GenAI - 3nd Yr- AI&DS,10,6,4,0,60%,Critical,6 more,2026-10-05,1
61,4MW25AD400,SAMPATH S HEBBAR,Data Science & GenAI - 3nd Yr- AI&DS,10,1,9,0,10%,Critical,26 more,2026-09-02,8

#### Section 1: Data Inspection

In [7]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
#-----------------------------Write Solution Code-----------------------------
# Display the first 10 rows
print("First 10 rows:")
display(df.head(10))

# Display the shape of the DataFrame
print("Shape of DataFrame:", df.shape)

# Display the data types of each column
print("Data types:")
print(df.dtypes)

First 10 rows:

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW23AD50,SRAJAN S,Data Science & GenAI - 3nd Yr- AI&DS,11,0,11,0,0%,Critical,33 more,Never,11
1,4MW24AD001,ADITHYA S POOJARY,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4,0,64%,Critical,5 more,2026-10-07,0
2,4MW24AD002,ANKITHA PRASANNA NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,11,0,0,100%,Safe,✓ Met,2026-10-07,0
3,4MW24AD003,ANUSHA KOTEGAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91%,Safe,✓ Met,2026-10-07,0
4,4MW24AD004,ANVITA RAMESH NAIK,Data Science & GenAI - 3nd Yr- AI&DS,11,9,2,0,82%,Warning,✓ Met,2026-10-07,0
5,4MW24AD005,ARPITHA M THANTRY,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0,73%,Critical,1 more,2026-10-07,0
6,4MW24AD007,ASNIYA,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91%,Safe,✓ Met,2026-10-07,0
7,4MW24AD008,B. G PRARTHANA HEBBAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91%,Safe,✓ Met,2026-10-07,0
8,4MW24AD009,BHARATHRAJ A NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,4,7,0,36%,Critical,17 more,2026-10-05,1
9,4MW24AD010,BHEEMA KATTIMANI,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0,73%,Critical,1 more,2026-10-07,0

Shape of DataFrame: (62, 12)
Data types:
Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [8]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
#-----------------------------Write Solution Code-----------------------------
# Check missing values in each column
print("Missing values in each column:")
print(df.isnull().sum())

# Display columns that contain missing values
print("\nColumns with missing values:")
print(df.isnull().sum()[df.isnull().sum() > 0])

# Check Last Present Date for "Never"
print("\nCount of 'Never' in Last Present Date:")
print(df["Last Present Date"].astype(str).str.strip().str.lower().eq("never").sum())

Missing values in each column:
Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64

Columns with missing values:
Series([], dtype: int64)

Count of 'Never' in Last Present Date:
5

In [9]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
#-----------------------------Write Solution Code-----------------------------
# Rename all columns to snake_case
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace("%", "pct", regex=False)
    .str.replace(r"[^\w]+", "_", regex=True)
    .str.strip("_")
)

# Display the updated column list
print("Updated column names:")
print(df.columns.tolist())

Updated column names:
['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75pct', 'last_present_date', 'consecutive_absences']

In [10]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
#-----------------------------Write Solution Code-----------------------------
# Convert attendance percentage to numeric values
df["attendance_pct"] = pd.to_numeric(
    df["attendance_pct"], errors="coerce"
)

# Display the first 5 rows
display(df.head())

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences
0,4MW23AD50,SRAJAN S,Data Science & GenAI - 3nd Yr- AI&DS,11,0,11,0,NaN,Critical,33 more,Never,11
1,4MW24AD001,ADITHYA S POOJARY,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4,0,NaN,Critical,5 more,2026-10-07,0
2,4MW24AD002,ANKITHA PRASANNA NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,11,0,0,NaN,Safe,✓ Met,2026-10-07,0
3,4MW24AD003,ANUSHA KOTEGAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,NaN,Safe,✓ Met,2026-10-07,0
4,4MW24AD004,ANVITA RAMESH NAIK,Data Science & GenAI - 3nd Yr- AI&DS,11,9,2,0,NaN,Warning,✓ Met,2026-10-07,0

#### Section 2: Filtering & Selection

In [11]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
#-----------------------------Write Solution Code-----------------------------
# Select students whose attendance is below 75%
low_attendance = df[df["attendance_pct"] < 75]

# Display the result
display(low_attendance)

Empty DataFrame
Columns: [roll_no, student_name, subject, total_classes, present, absent, excused, attendance_pct, status, classes_needed_75pct, last_present_date, consecutive_absences]
Index: []

In [12]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
#-----------------------------Write Solution Code-----------------------------
# Count students in each attendance status
status_count = df["status"].value_counts()

print(status_count)

status
Critical    32
Safe        23
Warning      7
Name: count, dtype: int64

In [13]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
#-----------------------------Write Solution Code-----------------------------
# (a) Display all Safe students using .loc
safe_students = df.loc[df["status"] == "Safe"]
display(safe_students)

# (b) Display the first 15 rows and columns 2 to 6 using .iloc
display(df.iloc[:15, 2:7])

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences
2,4MW24AD002,ANKITHA PRASANNA NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,11,0,0,NaN,Safe,✓ Met,2026-10-07,0
3,4MW24AD003,ANUSHA KOTEGAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,NaN,Safe,✓ Met,2026-10-07,0
6,4MW24AD007,ASNIYA,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,NaN,Safe,✓ Met,2026-10-07,0
7,4MW24AD008,B. G PRARTHANA HEBBAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,NaN,Safe,✓ Met,2026-10-07,0
14,4MW24AD015,K MANYA RAO,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,NaN,Safe,✓ Met,2026-10-07,0
15,4MW24AD016,KAVYA,Data Science & GenAI - 3nd Yr- AI&DS,11,11,0,0,NaN,Safe,✓ Met,2026-10-07,0
28,4MW24AD029,PRATHEEKSHA NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,11,0,0,NaN,Safe,✓ Met,2026-10-07,0
32,4MW24AD033,PRIYADARSHINI,Data Science & GenAI - 3nd Yr- AI&DS,10,10,0,0,NaN,Safe,✓ Met,2026-10-07,0
33,4MW24AD034,RAKSHITHA (ASHOK KUMAR),Data Science & GenAI - 3nd Yr- AI&DS,10,10,0,0,NaN,Safe,✓ Met,2026-10-07,0
35,4MW24AD036,RAMITHA R RAO,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,NaN,Safe,✓ Met,2026-10-07,0
39,4MW24AD040,SAKSHI,Data Science & GenAI - 3nd Yr- AI&DS,10,10,0,0,NaN,Safe,✓ Met,2026-10-07,0
42,4MW24AD043,SANJANA A MOOLYA,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,NaN,Safe,✓ Met,2026-10-05,1
43,4MW24AD044,SANVI SHETTIGAR,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,NaN,Safe,✓ Met,2026-10-07,0
44,4MW24AD045,SHARADHI,Data Science & GenAI - 3nd Yr- AI&DS,10,10,0,0,NaN,Safe,✓ Met,2026-10-07,0
46,4MW24AD047,SHETTY RAKSHA UDAY,Data Science & GenAI - 3nd Yr- AI&DS,10,10,0,0,NaN,Safe,✓ Met,2026-10-07,0
47,4MW24AD048,SHRADDHA NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,10,10,0,0,NaN,Safe,✓ Met,2026-10-07,0
48,4MW24AD049,SHRAVYA,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,NaN,Safe,✓ Met,2026-10-05,1
49,4MW24AD050,SHRI RAKSHA BHAT,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,NaN,Safe,✓ Met,2026-10-07,0
50,4MW24AD052,TASMIYA ANJUM,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,NaN,Safe,✓ Met,2026-10-07,0
51,4MW24AD053,THRISHA,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,NaN,Safe,✓ Met,2026-10-07,0
53,4MW24AD055,VAISHNAVI K AMIN,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,NaN,Safe,✓ Met,2026-10-07,0
54,4MW24AD056,VANDANA V DEVADIGA,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,NaN,Safe,✓ Met,2026-10-07,0
57,4MW24AD059,ZEHA AYESHA,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,NaN,Safe,✓ Met,2026-10-07,0

,subject,total_classes,present,absent,excused
0,Data Science & GenAI - 3nd Yr- AI&DS,11,0,11,0
1,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4,0
2,Data Science & GenAI - 3nd Yr- AI&DS,11,11,0,0
3,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0
4,Data Science & GenAI - 3nd Yr- AI&DS,11,9,2,0
5,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0
6,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0
7,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0
8,Data Science & GenAI - 3nd Yr- AI&DS,11,4,7,0
9,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0
10,Data Science & GenAI - 3nd Yr- AI&DS,11,6,5,0
11,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0
12,Data Science & GenAI - 3nd Yr- AI&DS,11,9,2,0
13,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4,0
14,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0

In [14]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
#-----------------------------Write Solution Code-----------------------------
# Filter students with consecutive absences >= 5
students_absent = df.loc[
    df["consecutive_absences"] >= 5,
    ["student_name", "status", "last_present_date"]
]

display(students_absent)

              student_name    status last_present_date
0                SRAJAN  S  Critical             Never
36  RISHAN FRANCIS MENEZES  Critical             Never
45           SHARANU PATIL  Critical             Never
52                UJWAL. K  Critical             Never
58        AMITH G PALANDYE  Critical             Never
61        SAMPATH S HEBBAR  Critical        2026-09-02

### Section 3: Grouping & Aggregation

In [15]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
#-----------------------------Write Solution Code-----------------------------
# Group by status and calculate summary statistics
summary = df.groupby("status").agg(
    student_count=("student_name", "count"),
    average_attendance=("attendance_pct", "mean"),
    max_consecutive_absences=("consecutive_absences", "max")
)

print(summary)

          student_count  average_attendance  max_consecutive_absences
status
Critical             32                 NaN                        11
Safe                 23                 NaN                         1
Warning               7                 NaN                         1

In [16]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
#-----------------------------Write Solution Code-----------------------------
# Create attendance categories
df["attendance_category"] = pd.cut(
    df["attendance_pct"],
    bins=[-1, 59.99, 74.99, 89.99, 100],
    labels=["Poor", "Average", "Good", "Excellent"]
)

# Count students in each category
category_count = df.groupby(
    "attendance_category", observed=False
).size()

print(category_count)

attendance_category
Poor         0
Average      0
Good         0
Excellent    0
dtype: int64

In [17]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
#-----------------------------Write Solution Code-----------------------------
# Calculate totals using agg()
totals = df.agg({
    "total_classes": "sum",
    "present": "sum",
    "absent": "sum"
})

print("Total Classes, Present and Absent:")
print(totals)

Total Classes, Present and Absent:
total_classes    650
present          454
absent           196
dtype: int64

In [18]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
#-----------------------------Write Solution Code-----------------------------
# Group by Status and calculate statistics
status_stats = df.groupby("status").agg({
    "present": ["min", "max", "mean"],
    "absent": "sum"
})

print(status_stats)

         present               absent
             min max      mean    sum
status
Critical       0   8  5.312500    168
Safe           9  11  9.695652     14
Warning        8   9  8.714286     14

### Section 4: Feature Engineering & Transformation

In [19]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
#-----------------------------Write Solution Code-----------------------------
# Calculate Risk Score
df["risk_score"] = (
    df["absent"] * 0.4
    + df["consecutive_absences"] * 0.6
)

# Display the top 10 students with the highest risk score
top_10_risk = df.sort_values(
    by="risk_score",
    ascending=False
).head(10)

display(top_10_risk)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences,attendance_category,risk_score
0,4MW23AD50,SRAJAN S,Data Science & GenAI - 3nd Yr- AI&DS,11,0,11,0,NaN,Critical,33 more,Never,11,NaN,11.0
36,4MW24AD037,RISHAN FRANCIS MENEZES,Data Science & GenAI - 3nd Yr- AI&DS,10,0,10,0,NaN,Critical,30 more,Never,10,NaN,10.0
52,4MW24AD054,UJWAL. K,Data Science & GenAI - 3nd Yr- AI&DS,10,0,10,0,NaN,Critical,30 more,Never,10,NaN,10.0
58,4MW24AD060,AMITH G PALANDYE,Data Science & GenAI - 3nd Yr- AI&DS,10,0,10,0,NaN,Critical,30 more,Never,10,NaN,10.0
45,4MW24AD046,SHARANU PATIL,Data Science & GenAI - 3nd Yr- AI&DS,10,0,10,0,NaN,Critical,30 more,Never,10,NaN,10.0
61,4MW25AD400,SAMPATH S HEBBAR,Data Science & GenAI - 3nd Yr- AI&DS,10,1,9,0,NaN,Critical,26 more,2026-09-02,8,NaN,8.4
26,4MW24AD027,PRAJWAL,Data Science & GenAI - 3nd Yr- AI&DS,11,3,8,0,NaN,Critical,21 more,2026-10-05,1,NaN,3.8
8,4MW24AD009,BHARATHRAJ A NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,4,7,0,NaN,Critical,17 more,2026-10-05,1,NaN,3.4
30,4MW24AD031,PRAVEEN KUMAR N,Data Science & GenAI - 3nd Yr- AI&DS,10,3,7,0,NaN,Critical,18 more,2026-10-07,0,NaN,2.8
31,4MW24AD032,PREETH SHETTY,Data Science & GenAI - 3nd Yr- AI&DS,10,5,5,0,NaN,Critical,10 more,2026-10-05,1,NaN,2.6

In [ ]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
#-----------------------------Write Solution Code-----------------------------
# Extract numeric values from the Classes Needed (75%) column
df["classes_needed_numeric"] = (
    df["classes_needed_75pct"]
    .astype(str)
    .str.extract(r"(\d+)", expand=False)
    .fillna("0")
    .astype(int)
)

display(df[["student_name", "classes_needed_75pct", "classes_needed_numeric"]])

# Display the result
display(
    df[[
        "student_name",
        "classes_needed_75pct",
        "classes_needed_numeric"
    ]]
)

              student_name classes_needed_75pct  classes_needed_numeric
0                SRAJAN  S              33 more                      33
1        ADITHYA S POOJARY               5 more                       5
2   ANKITHA PRASANNA NAYAK                ✓ Met                       0
3           ANUSHA KOTEGAR                ✓ Met                       0
4       ANVITA RAMESH NAIK                ✓ Met                       0
..                     ...                  ...                     ...
57             ZEHA AYESHA                ✓ Met                       0
58        AMITH G PALANDYE              30 more                      30
59      AMOGH BHASKAR NAIK              10 more                      10
60                CHANDISH               6 more                       6
61        SAMPATH S HEBBAR              26 more                      26

[62 rows x 3 columns]

KeyError: "['classes_needed_75_pct'] not in index"

In [ ]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
#-----------------------------Write Solution Code-----------------------------

In [ ]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
#-----------------------------Write Solution Code-----------------------------

### Section 5: Advanced Analysis

In [ ]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
#-----------------------------Write Solution Code-----------------------------

In [ ]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
#-----------------------------Write Solution Code-----------------------------

In [ ]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
#-----------------------------Write Solution Code-----------------------------

In [ ]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
#-----------------------------Write Solution Code-----------------------------